CREATE TABLE IF NOT EXISTS roster (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  speed TINYINT UNSIGNED NOT NULL DEFAULT 5,
  UNIQUE KEY uq_roster_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  json TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS game (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  state MEDIUMTEXT NOT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS players (
  token CHAR(32) NOT NULL PRIMARY KEY,
  roster_id INT UNSIGNED NOT NULL,
  team TINYINT UNSIGNED NULL,
  ready TINYINT(1) NOT NULL DEFAULT 0,
  joined_at DOUBLE NOT NULL,
  last_seen DOUBLE NOT NULL,
  UNIQUE KEY uq_players_roster (roster_id),
  CONSTRAINT fk_players_roster FOREIGN KEY (roster_id) REFERENCES roster (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO settings (id, json) VALUES (1, '{}');
INSERT IGNORE INTO game (id, state, version) VALUES (1, '{"phase":"lobby"}', 1);
